# Publish the library

name: Publish Library

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          make init
          make scrape
          make lib

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/lib/siemens.tar.gz
